name: Spec Main
# This workflow uploads the latest spec to the team spaces.

on:
  push:
    branches:
      - main
    paths:
      - 'specification/**'
      - 'spectral/**'

jobs:

  lint:
    name: Validate style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run linter
        run: make lint

  generate-main-preview:
    name: Generate Main Preview
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Bundle
        run: make bundle

      - uses: actions/upload-artifact@v2
        with:
          name: openapi-bundled
          path: tests/openapi-bundled.yaml

      - name: Upload Main spec
        run: >-
          aws s3 cp tests/openapi-bundled.yaml
          ${{ env.SPACES_PATH }}/DigitalOcean-public.v2.yaml
          --endpoint=${{ env.SPACES_ENDPOINT }}
          --acl public-read
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SPACES_ACCESS_SECRET }}
          AWS_DEFAULT_OUTPUT: json
          SPACES_PATH: ${{ secrets.SPACES_PATH }}
          SPACES_ENDPOINT: ${{ secrets.SPACES_ENDPOINT }}
          AWS_EC2_METADATA_DISABLED: true

  generate-and-push-python-client:
    name: Generate Python Client and Create PR
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Check out digitalocean-client-python repo
        uses: actions/checkout@v2
        with:
          repository: digitalocean/digitalocean-client-python
          token: ${{ secrets.WORKFLOW_TRIGGER_TOKEN }}
      
      - name: Generate Python client
        run: SPEC_FILE=tests/openapi-bundled.yaml make generate
      
      - name: Push updated generated Python Client
        run: gh pr create -H bot-regenerate-${GITHUB_SHA::7} -B main --title '[Bot] Re-generate Python Client' --body '[These changes to DigitalOcean spec][${{ github.event.inputs.commit_url }}] (digitalocean/openapi) triggered this regeneration of the python client.' -r owners -l automated pr